-- =============================================================================
-- Al Ameen Caps – Supabase Schema
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Profiles (extends auth.users)
-- -----------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  first_name text,
  last_name text,
  phone text,
  shipping_address jsonb,
  billing_address jsonb
);

-- -----------------------------------------------------------------------------
-- Products
-- -----------------------------------------------------------------------------
create table public.products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  stock_quantity int not null default 0,
  metadata jsonb,
  is_active boolean not null default true
);

-- -----------------------------------------------------------------------------
-- Orders
-- -----------------------------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'PENDING',
  total_amount numeric(10, 2) not null,
  payfast_pf_payment_id text unique,
  shipping_data jsonb
);

create index idx_orders_user_id on public.orders (user_id);
create index idx_orders_payfast_pf_payment_id on public.orders (payfast_pf_payment_id);

-- -----------------------------------------------------------------------------
-- Order Items (snapshots of product at time of order)
-- -----------------------------------------------------------------------------
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  quantity int not null check (quantity > 0),
  unit_price numeric(10, 2) not null,
  product_name text not null
);

create index idx_order_items_order_id on public.order_items (order_id);

-- =============================================================================
-- Row Level Security (RLS)
-- =============================================================================

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- -----------------------------------------------------------------------------
-- Products: read access for everyone (anon + authenticated)
-- -----------------------------------------------------------------------------
create policy "Products are viewable by everyone"
  on public.products for select
  using (true);

-- -----------------------------------------------------------------------------
-- Orders: read and insert for authenticated users (own data only)
-- -----------------------------------------------------------------------------
create policy "Users can view own orders"
  on public.orders for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own orders"
  on public.orders for insert
  to authenticated
  with check (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Order items: follow order access (read/insert with orders)
-- -----------------------------------------------------------------------------
create policy "Users can view own order items"
  on public.order_items for select
  to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id and o.user_id = auth.uid()
    )
  );

create policy "Users can insert order items for own orders"
  on public.order_items for insert
  to authenticated
  with check (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id and o.user_id = auth.uid()
    )
  );

-- -----------------------------------------------------------------------------
-- Profiles: read and update for authenticated users (own data only)
-- -----------------------------------------------------------------------------
create policy "Users can view own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Trigger: create profile on signup (optional but recommended)
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'first_name', ''),
    coalesce(new.raw_user_meta_data->>'last_name', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
