-- =============================================================================
-- Reservations table: store reservation form submissions (email + DB)
-- =============================================================================

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_email text not null,
  customer_phone text default '',
  items jsonb default '[]',
  total_amount numeric(10, 2) not null default 0,
  notes text default ''
);

create index if not exists idx_reservations_created_at on public.reservations (created_at desc);
create index if not exists idx_reservations_customer_email on public.reservations (customer_email);

alter table public.reservations enable row level security;

-- Only admins can read reservations (insert is done server-side with service role)
create policy "Admins can view all reservations"
  on public.reservations for select
  to authenticated
  using (public.is_admin());
